# Site settings
title: Your Name
description: Personal webpage
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag

# Exclude files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
