plugins:
  - jekyll-theme-minimal
  - jekyll-seo-tag

# Site settings
title: Keith Trnka
description: Personal website of Keith Trnka, PhD
logo: /assets/img/profile.jpg
baseurl: "/webpage" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Author settings (prevents "Your Name" in SEO tags)
author:
  name: Keith Trnka

# SEO settings
title_separator: "|"

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag

# Exclude files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
